version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=voice_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn voice_assistant.asgi:application --timeout 120 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - C:/Users/Admin/Desktop/GPT Assistant/voice_assistant/core/templates/core:/code/core/templates/core  # Map the _next folder

    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/voice_assistant
      - REDIS_URL=redis://redis:6379/0

  node:
    build: 
      context: ./web  # Specify the context for the build
      dockerfile: DOCKERFILE
    ports:
      - "3000:3000"  # Expose port 3000
    depends_on:
      - db
      - redis

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
